# Generated by Django 4.1.4 on 2022-12-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': '数据构造/处理', 'verbose_name_plural': '数据构造/处理'},
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='dealcontent',
        ),
        migrations.AddField(
            model_name='casenew',
            name='is_online',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='可线上执行'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='interfaceProcess',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='从接口返回中取值字典'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='interfaceRequest_body',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='从接口请求body参数中取值字典'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='interfaceRequest_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='从接口请求查询参数中取值字典'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='m_order',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='mongodb排序条件'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='m_query',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='mongodb查询条件'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='m_result',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='mongodb目的参数'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='m_table',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='mongodb操作表'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='m_type',
            field=models.IntegerField(choices=[(0, 'select'), (1, 'update')], default=0, verbose_name='mongodb操作类别'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='sqls',
            field=models.TextField(blank=True, null=True, verbose_name='mysql数据库语句'),
        ),
        migrations.AlterField(
            model_name='casenew',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='casenew',
            name='related',
            field=models.ManyToManyField(null=True, through='saas.relationship', to='saas.casenew'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='dealtype',
            field=models.IntegerField(choices=[(0, '获取接口返回值'), (1, 'mysql操作'), (2, 'mongodb操作'), (3, 'redis操作'), (4, '无后续操作'), (5, '仅获取接口query请求值'), (6, '仅获取接口body请求值')], default=4, verbose_name='数据操作类别'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relatedcase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedc', to='saas.casenew', verbose_name='关联用例'),
        ),
        migrations.CreateModel(
            name='configs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=2000, verbose_name='测试账号')),
                ('password', models.CharField(max_length=2000, verbose_name='测试账号密码')),
                ('platform', models.IntegerField(choices=[(0, '测试环境'), (1, '线上环境')], default=0, verbose_name='测试平台')),
                ('status', models.BooleanField(default=False, verbose_name='启用')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '参数配置',
                'verbose_name_plural': '参数配置',
            },
        ),
    ]
