# Generated by Django 4.1.4 on 2022-12-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_alter_relationship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.CharField(max_length=50, null=True, verbose_name='负责人'),
        ),
    ]
