# Generated by Django 4.1.4 on 2022-12-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_project_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='leader',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人'),
        ),
    ]
