# Generated by Django 4.1.4 on 2022-12-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_project_nameeng_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='casenew',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.module', verbose_name='所属模块'),
        ),
    ]
