# Generated by Django 4.1.4 on 2022-12-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_casenew_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casenew',
            name='name',
        ),
    ]
