# Generated by Django 4.1.4 on 2022-12-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_casenew_formal_case_alter_casenew_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='dealtype',
        ),
        migrations.AlterField(
            model_name='casenew',
            name='formal_case',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='正式的用例'),
        ),
        migrations.AlterField(
            model_name='casenew',
            name='is_online',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=False, verbose_name='可线上执行'),
        ),
    ]
