# Generated by Django 4.1.4 on 2022-12-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0010_alter_casenew_formal_case_alter_casenew_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenew',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas.module', verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='casenew',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='m_type',
            field=models.IntegerField(choices=[(0, 'select'), (1, 'update'), (2, '无操作')], default=3, verbose_name='mongodb操作类别'),
        ),
    ]
