# Generated by Django 4.1.4 on 2023-01-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0011_alter_casenew_module_alter_casenew_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='filetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='saas/saas_program/testFile', verbose_name='文件参数')),
            ],
            options={
                'verbose_name': '文件管理',
                'verbose_name_plural': '文件管理',
            },
        ),
    ]
